name: CityBuildSystem
version: 1.0-SNAPSHOT
author: TntTastisch
main: de.TntTastisch.BlackNerux.CityBuildSystem
commands:
  gamemode:
    aliases:
      - gm
  vanish:
    aliases:
      - v
  heal:
  feed:
  setspawn:
  spawn:
  fly:
  teleport:
    aliases:
      - tp
  tpall:
  tphere:
  home:
  delhome:
  sethome:
  tpa:
  tpahere:
  tpaall:
  tpatoggle:
  annehmen:
  ablehnen:
  socialspy:
  msg:
  msgtoggle:
  r:
  jobs:
    aliases:
      - job
  enderchest:
    aliases:
      - ec
  ptime:
  day:
  night:
  sign:
  invsee: